# Generated by Django 4.2.3 on 2023-07-04 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Совет', 'verbose_name_plural': 'Советы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pub_date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'Преподаватель или курс', 'verbose_name_plural': 'Преподаватели и курсы'},
        ),
        migrations.RemoveField(
            model_name='advice',
            name='username',
        ),
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
        migrations.AddField(
            model_name='advice',
            name='name',
            field=models.CharField(default='Anonymous', max_length=250, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='advice',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonymous', max_length=250, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Институт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advice',
            name='text',
            field=models.TextField(verbose_name='Совет'),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.CharField(choices=[('first', '1 курс'), ('second', '2 курс'), ('third', '3 курс'), ('fourth', '4 курс')], max_length=200, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='review',
            name='teacherOrCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher', verbose_name='Преподаватель или курс'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ФИО или название'),
        ),
    ]
