# Generated by Django 4.2.3 on 2023-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_advice_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='contacts',
            field=models.TextField(default=1, verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=1, upload_to='teachers/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
