# Generated by Django 4.2.3 on 2023-07-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_faq_teacher_contacts_teacher_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='advice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contacts',
            field=models.TextField(verbose_name='Ссылка на сайте УрФУ'),
        ),
    ]
